### ISSUE TITLE
CTX

### ISSUE THREAD

**Issue by LautaroStude** [mas-codigo/lol-bot#1]

**Comment by LautaroStude** [comment]
@RedYaafte por favor leelo

**Comment by RedYaafte** [comment]
@LautaroStude creo que encontraste el error de esta parte
``` python
async def rank(self, summoner: str, region: str):
# No es self es ctx.
```
En el video lo corrijo el error.
También agregue a la descripción del repo los pasos a seguir para usar el código.
Saludos.
